---
name: Packer

on:
  push:
  pull_request:

jobs:
  packer:
    runs-on: macos-10.15
    name: packer

    defaults:
      run:
        working-directory: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      
      - name: Install packer
        run: brew upgrade packer

      - name: Fix Template
        run: packer fix guix-vm.json

      - name: Validate Template
        run: packer validate -syntax-only guix-vm.json

      - name: Build Artifact
        run: packer build guix-vm.json