---
name: Packer

on:
  push:
  pull_request:

jobs:
  packer:
    runs-on: ubuntu-20.04
    name: packer

    defaults:
      run:
        working-directory: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: palfrey/packer-github-actions@working-directory
        with:
          command: fix
          working_directory: packer
          target: guix-vm.json

      # validate templates
      - name: Validate Template
        uses: palfrey/packer-github-actions@working-directory
        with:
          command: validate          
          arguments: -syntax-only
          working_directory: packer
          target: guix-vm.json

      # build artifact
      - name: Build Artifact
        uses: palfrey/packer-github-actions@working-directory
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          working_directory: packer
          target: guix-vm.json
